h: 100
delta_t: 10e-6
r: 0.01
R: 50
periphery_size: 1
q_plus_max: 15e-10
q_minus_max: 3e-9
Q_plus_s: 4e-4
Q_minus_s: 8e-4
resistance: 1
E_plus: 150000
E_minus: 300000
alpha: 5e-8
beta: 10
sigma: 1e-5
seed: 42
p_0: 0.0000007
L: 200
start_x: 0
start_y: 0
start_z: 8000
end_x: 0
end_y: 0
end_z: 10000
a: 1
degree_probability_growth: 2.5